version: "3"
services:
  postgres:
    hostname: postgres
    image: "postgres:11.10-alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      no_proxy: "127.0.0.1"
    ports:
      - "32768:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://postgres:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      venture_vista_local_net:


  ventureVistaUserInfoService:
    hostname: venture_vistauser_info_service
    image: venture_vistauser_info:local
    build:
      context: UserService
    ports:
      - "8080:8080"
    command: [ "npm", "run", "serve" ]
    environment:
      SQL_DB_URI: postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - "postgres"
    networks:
      venture_vista_local_net:
  
  ventureVistafrontend:
    hostname: venture_vistauser_frontend
    image: venture_vistauser_frontend:latest
    build:
      context: frontend
    ports:
      - "12345:80"
    deploy:
      resources:
        limits:
          memory: 126M
        reservations:
          memory: 50M

networks:
  venture_vista_local_net:
    driver: bridge
